language: python
python:
  - 2.7

notifications:
  email: false
  
before_install:
    # update aptitude
    - sudo apt-get update
    - sudo apt-get install -y python-opencv

    # help python importing cv and/or cv2
    - export PYTHONPATH=$PYTHONPATH:/usr/lib/pymodules/python2.7


install:
    # install python requirements
    - make setup
