language: python
python:
  - 2.7

notifications:
  email: false
  
before_install:
    # update aptitude
    - sudo apt-get update
    - sudo apt-get install -y python-opencv

    # help python importing cv and/or cv2
    - export PYTHONPATH=$PYTHONPATH:/usr/lib/pymodules/python2.7

    # verify all requirements were met
    - INSTALLDIR=$(python -c "import os; import numpy; import cv; import cv2; print(os.path.dirname(cv2.__file__))")

install:
    # install python requirements
    - make setup
